version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /:/srv
      - ./filebrowser:/config
    ports:
      - "30569:80"
    environment:
      - PUID=0
      - PGID=0
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: kimoji
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 38081:80